# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# If you look in the HTML files,
# you will see the settings below accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Deniz Altınbüken
google_analytics: UA-55641322-2
email:
description: >- # this means to ignore newlines until "baseurl:"
  Professional website of Deniz Altınbüken, Ph.D.
baseurl: ""
url: "http://denizaltinbuken.com" # the base hostname & protocol for your site, e.g. http://example.com
address: denizaltinbuken.com
twitter_username: denizaltinbuken
github_username:  denizalti
linkedin_username: denizalti

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - writing.markdown
  - publications.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
